Enhancement for Hue Init action test
GoogleCloudDataproc/initialization-actions pull request #1128
Opened 2024-01-17 08:20 UTC by prince-cs

Adding the hue test to submit the pyspark job with a python script which verifies, the basic hue functionalities.

2024-01-17 10:29 UTC, Deependra-Patel commented
/gcbrun

2024-01-22 17:26 UTC, functicons requested changes

2024-01-22 17:26 UTC, functicons commented on hue/run_queries.py
> +exit()
This is not necessary.

2024-01-22 17:26 UTC, functicons commented on hue/verify_hue_running.py
> +    def CheckMetadata(self, wait_seconds=5, max_retries=20):
make naming conventions consistent, use check_metadata here. Update other places as well.

2024-01-22 17:49 UTC, prince-cs commented on hue/run_queries.py
> +exit()
done

2024-01-22 17:49 UTC, prince-cs commented on hue/verify_hue_running.py
> +    def CheckMetadata(self, wait_seconds=5, max_retries=20):
done

2024-01-22 17:52 UTC, functicons approved these changes

2024-01-22 17:52 UTC, functicons commented
/gcbrun

2024-01-22 18:25 UTC, functicons commented
Presbumit failed:

```
2024-01-22T18:01:04.967134280Z FAILED (errors=1)
2024-01-22T18:01:04.967157156Z ================================================================================
2024-01-22T18:01:04.967164892Z ==================== Test output for //hue:test_hue (shard 1 of 3):
2024-01-22T18:01:04.967172159Z Running tests under Python 3.8.10: /usr/bin/python3
2024-01-22T18:01:04.967179463Z [  FAILED  ] setUpClass (__main__.HueTestCase)
2024-01-22T18:01:04.967186988Z ======================================================================
2024-01-22T18:01:04.967194356Z ERROR: setUpClass (__main__.HueTestCase)
2024-01-22T18:01:04.967201802Z ----------------------------------------------------------------------
2024-01-22T18:01:04.967209684Z Traceback (most recent call last):
2024-01-22T18:01:04.967217285Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/_main/bazel-out/k8-fastbuild/bin/hue/test_hue.runfiles/_main/integration_tests/dataproc_test_case.py", line 62, in setUpClass
2024-01-22T18:01:04.967239800Z     assert cls.PROJECT
2024-01-22T18:01:04.967247834Z AssertionError
```

2024-02-08 17:13 UTC, prince-cs commented
/gcbrun

2024-02-08 17:36 UTC, prince-cs commented
/gcbrun

2024-02-08 18:01 UTC, merged