Added new init action for Datasketches
GoogleCloudDataproc/initialization-actions pull request #1153
Opened 2024-03-01 17:31 UTC by kuldeepkk-dev

Added new initialization action for Apache Datasketches.

2024-03-01 17:31 UTC, kuldeepkk-dev commented
/gcbrun

2024-03-01 17:34 UTC, kuldeepkk-dev commented
/gcbrun

2024-03-01 19:09 UTC, cjac commented
You'll need to add a BUILD file and some tests for the CI framework for gcbrun to trigger.  Check with Erick ; he recently added some to an action that was missing them.

2024-03-04 18:48 UTC, functicons requested changes

2024-03-04 18:48 UTC, functicons commented on datasketches/datasketches.sh
> +#set -x
This should not be commented out. And the best practice is to use `set -euxo pipefail`

2024-03-04 18:48 UTC, functicons commented on datasketches/datasketches.sh
> +#Deploy spark java thetasketches example jar
Prefer extracting helper functions over comments. Consider structure like:

function main() {
  init
  configure_libraries
  download_example_jar
}

2024-03-04 22:12 UTC, functicons approved these changes
LGTM

2024-03-04 22:12 UTC, functicons commented
/gcbrun

2024-04-15 13:49 UTC, merged