update rapids version for 24.10 release
GoogleCloudDataproc/initialization-actions pull request #1248
Opened 2024-10-23 09:35 UTC by nvliyuan

This pr is to update the spark-rapids script version to 24.10.0 and update the readme doc

2024-10-24 02:11 UTC, nvliyuan commented
@viadea please help review. CC @jayadeep-jayaraman @cjac

2024-10-24 03:02 UTC, cjac commented
Oh hey, thanks for the ping.  I'll check it out.

2024-10-24 03:06 UTC, cjac commented
/gcbrun

2024-10-24 04:29 UTC, cjac requested changes
Let's get the docs updated to reflect the versions of Dataproc supported in Q4 2024

Our current supported versions follow:
2.2-debian12
2.1-debian11
2.0-debian10
2.2-ubuntu22
2.2-ubuntu20
2.0-ubuntu18
2.2-rocky9
2.1-rocky8
2.0-rocky8

And if all of these platforms are not supported by spark-rapids, then we'll need to merge in my changes to dask-rapids.

2024-10-25 07:22 UTC, nvliyuan commented on spark-rapids/README.md
> +    *   Ubuntu 20.04, Ubuntu 22.04, CentOS 7, or Rocky Linux 8, Debian 10, Debian 11
Thanks for pointing it out, we don't support centos7 now, update a link in the doc for the soft/hardware requirements.

2024-10-25 07:25 UTC, nvliyuan commented on spark-rapids/README.md
> +    --image-version=2.1-ubuntu20 \
update to 2.2 image

2024-10-28 06:31 UTC, nvliyuan commented on spark-rapids/README.md
> +    *   Ubuntu 20.04, Ubuntu 22.04, CentOS 7, or Rocky Linux 8, Debian 10, Debian 11
File related [pr](https://github.com/NVIDIA/spark-rapids/pull/11656) for the doc issue.

2024-11-05 07:30 UTC, nvliyuan commented
Hi @cjac , can we merge this pr?

2024-11-11 01:48 UTC, nvliyuan commented
Hi @cjac , any update?

2024-12-24 06:39 UTC, nvliyuan commented
Hi @cjac , not sure that can we merge this pr now?

2024-12-24 23:42 UTC, cjac commented
I haven't tested it thoroughly yet.  I've been caught up in refactoring shared code into templates.  I would like to generate this file from components rather than copy/pasting between scripts.

Can you let me know what you think of #1282 please?

2024-12-25 01:40 UTC, nvliyuan commented
Let's merge the pr for now, it is just a version update, thx

2024-12-25 02:12 UTC, cjac commented
let me try it in my environment...

2024-12-25 02:28 UTC, cjac commented
running without cuda-version specified produces a request for //developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda_12.1.1_530.30.02_linux.run

2024-12-25 02:31 UTC, cjac commented
incorrectly specifying rapids-runtime as `--metadata rapids-runtime="RAPIDS"` produces usable error message.

2024-12-25 02:55 UTC, cjac commented
@nvliyuan - do you mind if I commit to your branch?

2024-12-25 02:57 UTC, nvliyuan commented
please feel free to commit, thanks

2024-12-25 03:05 UTC, cjac commented
a re-re-re-run took 4m35.536s to complete ; This looks good to me.  Let me run it through the automated tests.

It looks like it built the kernel more than once.

NG code in templates/spark-rapids/ caches builds to GCS after the first run completes so subsequent similar runs will have less work to do.

[1] https://github.com/LLC-Technologies-Collier/initialization-actions/tree/template-gpu-20241219/templates/spark-rapids

2024-12-25 03:05 UTC, cjac commented
/gcbrun

2024-12-25 03:08 UTC, cjac commented
there's a known problem with our build system.  Un momento por favor.

2024-12-25 03:14 UTC, cjac commented
/gcbrun

2024-12-25 03:15 UTC, cjac commented
/gcbrun

2024-12-25 03:20 UTC, cjac commented
failure on 2.2-rocky9 ; I'll spin that up in my env.

2024-12-25 03:38 UTC, cjac commented
oof.  I forgot DKMS took so long to run.  I think the test is timing out for waiting on `dnf -y -q module install nvidia-driver:latest-dkms` maybe

2024-12-25 03:40 UTC, cjac commented
`dnf -y -q install cuda-toolkit` is taking a long time, too

2024-12-25 03:43 UTC, cjac commented
the run takes 14m9.444s on rocky9
```
# echo $?
0
```

2024-12-25 03:51 UTC, cjac commented
/gcbrun

2024-12-25 04:08 UTC, cjac commented
I'm sorry, I seem to have done something to the commit history here.  The diffstat looks very wrong at this point.

```
$ git diff master | diffstat
 CONTRIBUTING.md                         |   20 ++---
 cloudbuild/Dockerfile                   |   22 +++++-
 cloudbuild/presubmit.sh                 |    1 
 cloudbuild/run-presubmit-on-k8s.sh      |   34 +++++++--
 dask/dask.sh                            |  213 ++++++++++++++++++++++++++++++++++++++++++++--------------
 dask/test_dask.py                       |   14 +++
 gpu/Dockerfile                          |   40 +++++++++++
 gpu/README.md                           |   28 +++----
 gpu/bazel.screenrc                      |   11 +++
 gpu/env.json.sample                     |    7 +
 gpu/install_gpu_driver.sh               |  652 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------
 gpu/manual-test-runner.sh               |   77 +++++++++++++++++++++
 gpu/run-bazel-tests.sh                  |   24 ++++++
 gpu/test_gpu.py                         |  167 ++++++++++++++++++++++++++++++++-------------
 h2o/sample-script.py                    |   11 ---
 horovod/horovod.sh                      |    4 -
 horovod/test_horovod.py                 |   13 ++-
 hue/README.md                           |  118 ++++++++++++++++++++++++++++++++
 hue/another-query.png                   |binary
 hue/create-hive-table.png               |binary
 hue/hue-ui.png                          |binary
 hue/simple-hiveql.png                   |binary
 integration_tests/dataproc_test_case.py |   18 +++-
 rapids/BUILD                            |    2 
 rapids/Dockerfile                       |   40 +++++++++++
 rapids/bazel.screenrc                   |   17 ++++
 rapids/env.json.sample                  |    7 +
 rapids/manual-test-runner.sh            |   77 +++++++++++++++++++++
 rapids/rapids.sh                        |  814 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------
 rapids/run-bazel-tests.sh               |   23 ++++++
 rapids/test_rapids.py                   |  137 +++++++++++--------------------------
 rapids/verify_rapids_dask.py            |   19 -----
 rapids/verify_rapids_dask_yarn.py       |   19 +++++
 spark-rapids/README.md                  |   19 -----
 spark-rapids/spark-rapids.sh            |   14 ++-
 35 files changed, 1943 insertions(+), 719 deletions(-)

```

2024-12-25 04:10 UTC, cjac commented
my apologies.  ambiguous use of 'master' here.  When diffed against master's commit, 169e98e424d87833e10b7761130f08bfde4b4815 I see what I expect.

2024-12-25 04:22 UTC, cjac commented
/gcbrun

2024-12-25 04:31 UTC, cjac commented
many tests have passed.  still standing by for full green run.

2024-12-25 04:53 UTC, cjac commented
okay, that looks good.

2024-12-25 04:56 UTC, cjac approved these changes
LGTM.

2024-12-25 04:57 UTC, merged