[gpu] toward a more consistent driver and CUDA install
GoogleCloudDataproc/initialization-actions pull request #1275
Opened 2024-12-13 06:44 UTC by cjac

gpu/install_gpu_driver.sh

* exclusively using .run file installation method when available
* build nccl from source
* cache build artifacts from kernel driver and nccl
* Tested more CUDA minor versions
* gathering CUDA and driver version from URLs if passed
* Printing warnings when combination provided is known to fail
* waiting on apt lock when it exists
* wrapping expensive functions in completion checks to reduce re-run time
* fixed a problem with ops agent not installing ; using venv
* Installing gcc-12 on ubuntu22 to fix kernel driver FTBFS
* setting better spark defaults
* skipping proxy setup if http-proxy metadata not set
* added function to check secure-boot and os version compatability

gpu/manual-test-runner.sh

* order commands correctly

gpu/test_gpu.py

* clearer test skipping logic
* added instructions on how to test pyspark

2024-12-13 06:44 UTC, cjac commented
/gcbrun

2024-12-13 07:50 UTC, cjac commented
/gcbrun

2024-12-14 01:16 UTC, cjac commented
/gcbrun

2024-12-14 01:48 UTC, cjac commented
/gcbrun

2024-12-14 03:27 UTC, cjac commented
Tests took 43 minutes to run this time.  I think it's because the binary driver build cache was invalidated.  Let's see if this one takes more like 14 minutes.

2024-12-14 03:33 UTC, cjac commented
the intention is for this PR to resolve issue #1268

2024-12-14 03:39 UTC, cjac commented on cloudbuild/Dockerfile
> +    bazel_version=7.4.0 \
Pinning to 7.4.0 is necessary since the release of and default set to version 8

2024-12-14 03:39 UTC, cjac commented on cloudbuild/Dockerfile
> +RUN /usr/bin/curl -s https://bazel.build/bazel-release.pub.gpg | \
reduce noise in docker build with the -s (silent) option

2024-12-14 03:41 UTC, cjac commented on cloudbuild/Dockerfile
> +RUN update-alternatives --install /usr/bin/bazel bazel /usr/bin/bazel-${bazel_version} 1 && \
The file /usr/bin/bazel does not exist in the bazel-${version} package ; set up an alternative and use it

2024-12-14 03:41 UTC, cjac commented on cloudbuild/create-key-pair.sh
> +#!/bin/bash
this file copied from https://github.com/GoogleCloudDataproc/custom-images/tree/2024.11/examples/secure-boot

2024-12-14 03:42 UTC, cjac commented on cloudbuild/presubmit.sh
> +      continue
must remove this before merging

2024-12-14 03:46 UTC, cjac commented
slightly longer than the 14 minutes I predicted, this run completed in 16:29

2024-12-14 04:12 UTC, cjac commented on gpu/test_gpu.py
> +    ("KERBEROS", ["m", "w-0", "w-1"], GPU_T4, GPU_T4, "12.6", 'rocky', '2.2'),
We now exercise Kerberos in this test suite.  True, it's only tested on 2.2-rocky9 with CUDA 12.6, but we could change any of the STANDARD definitions above to KERBEROS to improve that set.

2024-12-14 04:15 UTC, cjac commented
/gcbrun

2024-12-14 04:43 UTC, cjac commented
/gcbrun

2024-12-14 07:17 UTC, cjac commented
/gcbrun

2024-12-14 19:55 UTC, cjac commented
/gcbrun

2024-12-14 20:27 UTC, cjac commented
/gcbrun

2024-12-14 21:38 UTC, cjac commented
/gcbrun

2024-12-14 21:57 UTC, cjac commented
/gcbrun

2024-12-14 23:19 UTC, cjac commented
/gcbrun

2024-12-15 01:32 UTC, cjac commented
/gcbrun

2024-12-15 03:17 UTC, cjac commented
/gcbrun

2024-12-15 03:52 UTC, cjac commented
/gcbrun

2024-12-15 04:11 UTC, cjac commented
okay, taking a little break...

2024-12-15 23:36 UTC, cjac commented
/gcbrun

2024-12-16 02:15 UTC, cjac commented
/gcbrun

2024-12-16 02:36 UTC, cjac commented
/gcbrun

2024-12-24 04:27 UTC, cjac commented
/gcbrun

2024-12-24 05:18 UTC, jayadeep-jayaraman commented
There are too many changes in this single PR. Can the PR be broken into smaller logical chunks so that it can be reviewed better

2024-12-24 07:40 UTC, cjac commented
yeah, there has been a lot of change.  I'll re-order the functions a little.  This should reduce the delta significantly.  Testing my change before commit and push...

2024-12-24 18:06 UTC, cjac commented
/gcbrun

2024-12-24 18:15 UTC, cjac commented
blocked on #1283

2024-12-25 22:54 UTC, cjac reviewed
These change are ready for review.

2025-01-07 18:11 UTC, SurajAralihalli commented
Referencing a related discussion: [https://github.com/GoogleCloudDataproc/initialization-actions/pull/1269#discussion_r1904787650](https://github.com/GoogleCloudDataproc/initialization-actions/pull/1269#discussion_r1904787650).

2025-01-13 21:36 UTC, cjac commented
> blocked on #1283

1283 has been merged ; continuing.

2025-01-13 22:01 UTC, cjac commented
> /usr/bin/nvidia-smi -i 0 --multi-instance-gpu 1

This command causes problems on 11.6.  I'm reviewing nvidia-smi -h for analog for that release.

2025-01-13 22:03 UTC, cjac commented
it wants an = for the last key/value pair but the first one must not have an =.  *shrug*

2025-01-14 02:39 UTC, cjac commented
/gcbrun

2025-01-14 02:52 UTC, cjac commented
rebased on master

2025-01-14 02:52 UTC, cjac commented
/gcbrun

2025-01-14 22:33 UTC, cjac commented
/gcbrun

2025-01-15 00:11 UTC, cjac commented
/gcbrun

2025-01-15 05:59 UTC, cjac commented
/gcbrun

2025-01-15 16:41 UTC, cjac commented
/gcbrun

2025-01-21 20:05 UTC, cjac commented
/gcbrun

2025-01-21 21:48 UTC, cjac commented
/gcbrun

2025-01-22 03:48 UTC, cjac commented
/gcbrun

2025-01-22 03:49 UTC, cjac commented
/gcbrun

2025-01-22 05:06 UTC, cjac commented
/gcbrun

2025-01-22 05:22 UTC, cjac commented
/gcbrun

2025-01-22 06:53 UTC, cjac commented
/gcbrun

2025-01-22 08:13 UTC, cjac commented
okay.  I think this will do.  Kuldeep, over to you.

2025-01-22 08:14 UTC, cjac commented
I'm going to do a review of the squash and see if anything needs cleaning up.

2025-01-22 08:31 UTC, cjac commented
/gcbrun

2025-01-22 09:06 UTC, cjac commented
okay.  it's a lot, but it all looks okay and has been thoroughly and repeatedly tested. Nota Bene that 'continue' in presubmit.sh ; I'll remove that once I receive an LGTM.

2025-01-23 00:32 UTC, cjac commented
/gcbrun

2025-01-23 01:21 UTC, cjac commented
/gcbrun

2025-01-23 02:34 UTC, cjac commented
/gcbrun

2025-01-23 04:57 UTC, cjac commented
/gcbrun

2025-01-23 14:50 UTC, cjac commented
/gcbrun

2025-01-23 15:56 UTC, cjac commented
/gcbrun

2025-01-23 19:30 UTC, cjac commented
/gcbrun

2025-01-24 01:24 UTC, cjac commented
/gcbrun

2025-01-24 02:49 UTC, cjac commented
/gcbrun

2025-01-24 02:53 UTC, cjac commented
Capacity Scheduler does not support gpu resources on Dataproc 2.0, so in order to use spark with yarn, fall back to Fair Scheduler ; I know there are concurrency concerns at high load, but that concern can be managed, and there is no other option on 2.0 clusters.

2025-01-24 05:34 UTC, cjac commented
/gcbrun

2025-01-24 06:52 UTC, cjac commented
* if cuda version and gpu driver version are not specified with metadata values, but the customer supplies a cuda runfile url, extract the driver and cuda version from the filename.
* There are inconsistencies between the driver version mentioned in the filename and the actual driver version that can be installed - I have mapped these out, so that if customer uses the latest minor version of any cuda release from 11.7 through 12.6.3 we have a known good driver for that cuda version without their having to think about it.  We also have likely to work configurations from 10.0 through 11.6 if the customer is willing to run an older dataproc subminor version with equally older kernels.
* Customer can explicitly specify driver version with either gpu-driver-version or gpu-driver-url metadata value
* selecting default cuda version based on dataproc image version
* The Yarn Capacity scheduler from hadoop [3.2.4](https://hadoop.apache.org/docs/r3.2.4/) does not recognize the gpu resource type and so must be replaced with the Fair scheduler.  NB: The Fair scheduler has problems at high concurrency when underprovisioned and will time out.
* NCCL is now built from source which takes a long first time for each cuda version per dataproc image the customer deploys. Which reminds me that
* tasks which used to take a long time to perform in previous versions of this script have had their results cached so that subsequent deployments of the same configuration will take significantly less time.

2025-01-24 17:42 UTC, kuldeepkk-dev reviewed
LGTM. 

@cjac I would recommend getting one more review from the product team since there are lot of changes.

2025-01-26 16:41 UTC, prince-cs commented on cloudbuild/presubmit.sh
> +      continue # to be removed before merge
this can be removed

2025-01-28 22:22 UTC, cjac commented
I met with customer to exercise the cluster and they asked for one additional change.  If the correct metadata key/value pair are passed, we now install pytorch and register a new kernel for use with JupyterLab.

2025-01-28 22:29 UTC, cjac commented
/gcbrun

2025-01-29 22:34 UTC, cjac commented
/gcbrun

2025-01-30 00:58 UTC, cnauroth requested changes
Thanks for this, @cjac ! I entered a few comments. In general, can we also review the `curl` calls to make sure they have the necessary retries?

2025-01-30 00:58 UTC, cnauroth commented on gpu/install_gpu_driver.sh
> +    mv /tmp/sshd_config_new /etc/ssh/sshd_config
Update to `mv -f`.

2025-01-30 00:58 UTC, cnauroth commented on gpu/install_gpu_driver.sh
> +      if   version_lt "${SPARK_VERSION}" "3.2" ; then DATAPROC_IMAGE_VERSION="2.0"
Are there any cases where neither `DATAPROC_IMAGE_VERSION` nor `DATAPROC_VERSION` is set so we need to do this detection based on Spark version? I would not have expected this.

2025-01-30 00:58 UTC, cnauroth commented on gpu/install_gpu_driver.sh
> +#    | perl -p -e "s{^gpgkey=.*$}{gpgkey=file://${kr_path}}" \
Can this commented-out code be removed?

2025-01-30 07:08 UTC, cjac reviewed
Thank you for the review, Chris and Prince.  I will make these changes and resolve each.

2025-01-30 07:08 UTC, cjac commented on gpu/test_gpu.py
> +    self.skipTest("No need to regularly test installing the agent on its own cluster ; this is exercised elsewhere")
I could go either way.  It feels excessive to me.  This is an expensive test that doesn't really exercise another code path.  I test with install-gpu-agent=true in my reproduction environment during development.

What do you think?

2025-01-30 07:08 UTC, cjac commented on gpu/install_gpu_driver.sh
> +  clear_nvsmi_cache
good catch.  I think I accidentally merged this line in from my template work.  I've got some code to cache results of nvidia-smi to XML to avoid excessively requesting the same information.  Too many executions of nvidia-smi tends to bog the system down.  I've upated the getGpusResources.sh script to cache the results, too, since the value never changes ; no GPUs are attached or removed during node lifetime.

2025-01-30 07:08 UTC, cjac commented on gpu/install_gpu_driver.sh
> +if test -f "${resources_json}" ; then cat "${resources_json}" ; exit 0 ; fi
this is to cache the result of nvidia-smi.  The result does not change, and each request is a heavy operation on the GPU.  Rather than running nvidia-smi every time that yarn wants to know about GPU resources, we instead cat the file with the results of the first request.

2025-01-30 07:08 UTC, cjac commented on gpu/install_gpu_driver.sh
> +      if   version_lt "${SPARK_VERSION}" "3.2" ; then DATAPROC_IMAGE_VERSION="2.0"
Yes.  When running the init action scripts as custom-images input

2025-01-30 19:27 UTC, cnauroth commented on gpu/test_gpu.py
> +    time.sleep( 3 + random.randint(1, 30) )
Oh, now I get it! Thanks for clarifying.

2025-01-30 21:13 UTC, cnauroth commented on gpu/test_gpu.py
> +    self.skipTest("No need to regularly test installing the agent on its own cluster ; this is exercised elsewhere")
If it's exercised elsewhere, then should we remove the test entirely instead of skipping it?

2025-01-30 21:17 UTC, cnauroth commented on gpu/install_gpu_driver.sh
> +if test -f "${resources_json}" ; then cat "${resources_json}" ; exit 0 ; fi
Got it, I missed the broader context that this is ultimately executed inside the GPU discovery script, which we are generating here.

2025-01-30 21:18 UTC, cnauroth commented on gpu/install_gpu_driver.sh
> +      if   version_lt "${SPARK_VERSION}" "3.2" ; then DATAPROC_IMAGE_VERSION="2.0"
I hadn't thought of that use case. Can you please add a comment that the final else path is meant to support custom image builds?

2025-01-31 21:39 UTC, cjac commented on gpu/test_gpu.py
> +    self.skipTest("No need to regularly test installing the agent on its own cluster ; this is exercised elsewhere")
that seems reasonable

2025-01-31 21:44 UTC, cjac commented on gpu/install_gpu_driver.sh
> +      if   version_lt "${SPARK_VERSION}" "3.2" ; then DATAPROC_IMAGE_VERSION="2.0"
sure thing

2025-01-31 21:45 UTC, cjac commented on gpu/install_gpu_driver.sh
> +#    | perl -p -e "s{^gpgkey=.*$}{gpgkey=file://${kr_path}}" \
https://issuetracker.google.com/issues/393219117

2025-01-31 21:47 UTC, cjac commented on gpu/install_gpu_driver.sh
> -    local kr_path=/usr/share/keyrings/cuda-archive-keyring.gpg
I did patch it back in.

2025-02-02 00:25 UTC, cjac commented
/gcbrun

2025-02-03 21:03 UTC, cjac commented
@cnauroth - I believe that I addressed all of your concerns in the previous change, https://github.com/GoogleCloudDataproc/initialization-actions/pull/1275/commits/eacb99f5d57ea4a3a993a181747d87071ca73108

Please let me know if you see anything that needs further attention.

2025-02-03 23:20 UTC, cnauroth commented on gpu/install_gpu_driver.sh
> +#latest="$(curl -s https://us.download.nvidia.com/XFree86/Linux-x86_64/latest.txt | awk '{print $1}')"
Remove this line if `latest` is no longer being used?

2025-02-03 23:20 UTC, cnauroth commented on gpu/install_gpu_driver.sh
> +      if gsutil ls -j "${gcs_tarball}.building" > "${local_tarball}.building.json" ; then
Is `-j` a recent new feature? I couldn't find this option in my `gsutil`.

2025-02-03 23:24 UTC, cjac commented on gpu/install_gpu_driver.sh
> +      if gsutil ls -j "${gcs_tarball}.building" > "${local_tarball}.building.json" ; then
it dumps the object metadata in JSON format ; I thought it would be `--format json` to match other gcloud commands, but I guess that it's slightly different because of gsutil.  The argument is documented for `gcloud storage ls --help` which I assumed used the same ABI as gsutil, but I don't see the argument in the `gcloud ls --help` documentation.

2025-02-03 23:38 UTC, cjac commented on gpu/install_gpu_driver.sh
> +      if gsutil ls -j "${gcs_tarball}.building" > "${local_tarball}.building.json" ; then
as for whether it's new, I don't think it is.  I looked through the release history[1], and it seems that JSON support has been included from the beginning.  But I couldn't find the argument parsing code where the argument is detected on a quick review of [2].

[1] https://github.com/GoogleCloudPlatform/gsutil/blob/master/CHANGES.md
[2] https://github.com/GoogleCloudPlatform/gsutil

2025-02-03 23:40 UTC, cjac commented
/gcbrun

2025-02-04 22:16 UTC, cjac commented
/gcbrun

2025-02-04 22:17 UTC, cjac commented
2.2.44-rocky9 is able to build the kernel driver, so I've removed the test skip for rocky9.

2025-02-04 22:44 UTC, cnauroth approved these changes
@cjac , that addresses all of my feedback. Thank you very much!

LGTM, pending a successful CI run on the latest changes.

@prince-cs and @kuldeepkk-dev , please let us know if you had any other feedback.

2025-02-06 19:49 UTC, merged