[mlvm] adding dask + maintence updates
GoogleCloudDataproc/initialization-actions pull request #836
Opened 2020-11-18 18:27 UTC by bradmiro

- Added `dask` init action
- Updated package versions
- Now uses temporary mamba environment to install conda packages
- Updated README to reflect changes
- Conflict with `r-xgboost` and RAPIDS; will not install the former if the latter is requested
- Issues `mxnet` and `rpy2` with conda. Moved to pip, as their respective communities suggest.
- Temporary fix to b/172686137 by uninstalling `pyarrow`

2020-11-25 15:54 UTC, medb requested changes

2020-11-25 15:54 UTC, medb commented on integration_tests/dataproc_test_case.py
> +        cmd = cmd + " --scp-flag=\"-oProxyCommand corp-ssh-helper %h %p\"" if "gcloud compute scp" in cmd else cmd
Why is this necessary?

2020-11-25 15:54 UTC, medb commented on mlvm/BUILD
>          "//rapids:rapids.sh",
Sort dependencies in alphabetical order

2020-11-25 15:54 UTC, medb commented on mlvm/mlvm.sh
> +
Remove extra space

2020-11-25 15:54 UTC, medb commented
/gcbrun

2020-11-25 17:12 UTC, bradmiro commented on integration_tests/dataproc_test_case.py
> +        cmd = cmd + " --scp-flag=\"-oProxyCommand corp-ssh-helper %h %p\"" if "gcloud compute scp" in cmd else cmd
Oops, reverted

2020-11-25 17:12 UTC, bradmiro commented on mlvm/BUILD
>          "//rapids:rapids.sh",
Done

2020-11-25 17:12 UTC, bradmiro commented on mlvm/mlvm.sh
> +
Done

2020-12-07 18:33 UTC, bradmiro commented
Can we try testing this again?

2020-12-08 01:09 UTC, bradmiro commented
The test failed because it ran tests that... it was supposed to skip:
https://github.com/GoogleCloudDataproc/initialization-actions/blob/e103b33cfe5ae5620c8715506bab6241f38dac6b/mlvm/test_mlvm.py#L122

Oddly enough, this worked completely fine locally. Not sure what happened. I also rebased, maybe we should try again?

2020-12-09 00:17 UTC, medb requested changes

2020-12-09 18:16 UTC, bradmiro commented on mlvm/README.md
> +  - executableFile: gs://dataproc-initialization-actions/mlvm/mlvm.sh
Done

2020-12-09 18:16 UTC, bradmiro commented on mlvm/README.md
>      --initialization-actions gs://dataproc-initialization-actions/mlvm/mlvm.sh \
Fixed

2020-12-10 06:51 UTC, medb approved these changes

2020-12-10 06:52 UTC, merged